DATAS SEGMENT
TABLE DB 01H,2H,3H,4H,5H,6H,7H,8H,9H,10
SUM   DW ?
DATAS ENDS



CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS
START:
        MOV AX,DATAS
        MOV DS,AX
        MOV ES,AX
        LEA SI,TABLE
        MOV CX,0AH
        XOR AX,AX
s:   ADD AL,[SI]
		ADC AH,0
        INC SI
        LOOP s
        MOV SUM, AX
CODES ENDS
END START